#!/bin/bash
### BEGIN INIT INFO
# Provides:          tvheadend
# Required-Start:    $local_fs $remote_fs udev
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

# Author: Andreas Öman

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/usr/sbin:/usr/bin:/sbin:/bin
DESC="Tvheadend"
NAME=tvheadend
DAEMON=/usr/bin/$NAME
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
LOGFILE=/tmp/out.log

##################
# CODE HERE
# Debug command
#chown -R root.root /dev/dvb/adapter0
dvbpath=/dev/dvb/adapter0
dvbgroup=$(ls -ld /dev/dvb/adapter0 | awk '{print $4}')
#ls -ld $dvbpath >> $LOGFILE

#echo "------------- TVHEADEND LOG ------------" >> $LOGFILE
#echo $(/bin/date) >> $LOGFILE

# check existence of the adapter directory
[ -d "$dvbpath" ] && E="The dvb directory exists" || E="The dvb directory does NOT exist -- waiting" waiting=1
#echo "$E" >> $LOGFILE
[ "$waiting" == "1" ] && sleep 20

# check existence of the adapter directory
[ -d "$dvbpath" ] && E="The dvb directory exists. Test 2" || E="The dvb directory does NOT exist -- exiting" exitnow=1
#echo "$E" >> $LOGFILE
[ "$exitnow" == "1" ] && exit

# checking whether the file is writable or not and changing permissions
#echo "DVB Group:" $dvbgroup >> $LOGFILE
[ "$dvbgroup" != "video" ] && F="The path is changed for group video" || F="The path is already changed for group VIDEO"
#chown -R root.video $dvbpath
chown hts.video $dvbpath
#echo "$F" >> $LOGFILE
#ls -ld $dvbpath >> $LOGFILE

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Configure command line options
[ "$TVH_ENABLED" = "1" ] || exit 0

ARGS="-f"
[ -z "$TVH_USER"      ] || ARGS="$ARGS -u $TVH_USER"
[ -z "$TVH_GROUP"     ] || ARGS="$ARGS -g $TVH_GROUP"
[ -z "$TVH_CONF_DIR"  ] || ARGS="$ARGS -c $TVH_CONF_DIR"
[ -z "$TVH_ADAPTERS"  ] || ARGS="$ARGS -a $TVH_ADAPTERS"
[ "$TVH_IPV6" = "1"   ] && ARGS="$ARGS -6"
[ -z "$TVH_HTTP_PORT" ] || ARGS="$ARGS --http_port $TVH_HTTP_PORT"
[ -z "$TVH_HTTP_ROOT" ] || ARGS="$ARGS --http_root $TVH_HTTP_ROOT"
[ -z "$TVH_HTSP_PORT" ] || ARGS="$ARGS --htsp_port $TVH_HTSP_PORT"
[ -z "$TVH_ARGS"      ] || ARGS="$ARGS $TVH_ARGS"
[ "$TVH_DEBUG" = "1"  ] && ARGS="$ARGS -s"

# Load the VERBOSE setting and other rcS variables
[ -f /etc/default/rcS ] && . /etc/default/rcS

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
#. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{
	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running
	#   2 if daemon could not be started
#        udevadm settle
#/usr/bin/tvheadend -s -u "$TVH_USER" -g "$TVH_GROUP"
## TEMP deactivated
        /sbin/start-stop-daemon -o --make-pidfile --pidfile "$PIDFILE" --start \
            -u "$TVH_USER" -g "$TVH_GROUP" --chuid "$TVH_USER:$TVH_GROUP" --chdir "$PWD" -b -a "$DAEMON"
############
#         su -l hts -c "/usr/bin/tvheadend -c $TVH_CONF_DIR -a $TVH_ADAPTERS -p $PIDFILE" > /dev/null \
#		|| return 1
#	 su -l hts -c "start-stop-daemon --start --quiet \
#              --pidfile $PIDFILE --exec $DAEMON " -- \
#		$ARGS \
#		|| return 2
}

#
# Function that stops the daemon/service
#
do_stop()
{
	# Return
	#   0 if daemon has been stopped
	#   1 if daemon was already stopped
	#   2 if daemon could not be stopped
	#   other if a failure occurred

        if [ -e "$PIDFILE" ]; then
          /sbin/start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
          #start-stop-daemon --stop --pidfile "$PIDFILE" --name "$NAME"
        else
          /sbin/start-stop-daemon --stop --quiet --name "$NAME"
        fi
	RETVAL="$?"
	[ "$RETVAL" = 2 ] && return 2
	# Many daemons don't delete their pidfiles when they exit.
	rm -f $PIDFILE
	return "$RETVAL"

}

case "$1" in
  start)
	[ "$VERBOSE" != no ]
# && log_daemon_msg "Starting $DESC" "$NAME" 
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ];; 
#&& log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ];; 
#&& log_end_msg 1 ;;
	esac
	;;
  stop)
	[ "$VERBOSE" != no ]
# && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ];; 
#&& log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ];; 
#&& log_end_msg 1 ;;
	esac
	;;
  restart|force-reload)
	#
	# If the "reload" option is implemented then remove the
	# 'force-reload' alias
	#
#	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
			0) log_end_msg 0 ;;
			1) log_end_msg 1 ;; # Old process is still running
			*) log_end_msg 1 ;; # Failed to start
		esac
		;;
	  *)
	  	# Failed to stop
		log_end_msg 1
		;;
	esac
	;;
  status)
        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
        ;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 3
	;;
esac

:
